### ISSUE TITLE
User invitation link

### ISSUE THREAD

**Issue by Ihor-BA** [ita-social-projects/Home-UI#100]
**Description**
As a User I want to use email invitation link, so that I can register in the system with a great ease.

**Preconditions:**
Cooperation admin shall send to user email with invitation link and register key due to user role.
**Acceptance criteria**
1.	If invitation link contains query parameters, email and registration key input fields at registration page displayed prefilled and blocked for further edition.
2.	When email invitation link does not contain query parameters, it shall redirect user to registration page where all fields at registration form should be opened for fulfilling by the user.

Equal to https://home-project-engineering.atlassian.net/browse/HP-34

User Stories - Registration user (User sign up) can be reached by following links:
https://github.com/ita-social-projects/Home-UI/issues/22#issue-991875934
https://home-project-engineering.atlassian.net/browse/HP-13

**Comment by Naira21** [comment]
Closed by pullrequest **Change registration link in the invitation letter #446**
