### ISSUE TITLE
Invitation section

### ISSUE THREAD

**Issue by Ihor-BA** [ita-social-projects/Home-UI#121]
**Description**
As a cooperation admin, I want to have an invitation section in the system so that I can easily send invitations to cooperation participants.

**Preconditions:** Cooperation admin already signs in the system.

**Acceptance criteria:**

The «Invitation» section should be available on the sidebar menu.

When the «Invitation» section on the sidebar menu is chosen, the main window shall display a list of invitations.

The list of invitations includes email, short address, invitation status and options.

Email, short address, Street, House number, Apartment number should be sortable with search inputs.

The short address includes Street, House number, Apartment number.

Invitation statuses are: processing  -  while the system creates invitation email;  pending - invitation email sent, but the user does not sign up the system yet;  accepted - invitation accepted, user complete sign-up process.

 Every list position has a dropdown menu that allows cooperation admin to delete invitation (Delete invitation TBD in separate user story) or create other invitation depending on the selected one (Сreate other invitation depends on the selected one - TBD in separate user story).

Button “Сreate invitation” for creating a new invitation should be available at the main window.

![invitation_section](https://user-images.githubusercontent.com/62280063/140046464-794922ac-17fd-4070-a03e-00538eb793f9.jpg)

**Corresponding titles:**
Processing - запрошення ствонено
Pending - очікує схвалення
Accepted - запрошення прийнято

[https://home-project-engineering.atlassian.net/browse/HP-36](url)

**Comment by KhrystynaHarasym** [comment]
An invitation expires (status - overdue) 7 days after the email with invitation was sent.
