### ISSUE TITLE
Starting page

### ISSUE THREAD

**Issue by Ihor-BA** [ita-social-projects/Home-UI#19]
As a user, I want to visit Starting page to overview system features so I can understand pros of system usage

**Acceptance criteria**
1. The header of the page has to have a system logo and a “Log in” button
2. Body of the page should contain a description of the main system features that users will get from the system, pros for cooperation manager, system advantages over similar solutions.
3. Bottoм of the page has to have a “Register cooperation” button.

**Assumptions:**
Body of page most sure could contain in future promotion video content and support contact block

[https://home-project-engineering.atlassian.net/browse/HP-14](url)

**Comment by maveric-ui** [comment]
FE: 20h
