### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by Ihor-BA** [ita-social-projects/Home-UI#23]
**Description**
As a registered user, I want to log in with my email and password so that the system can authenticate me.

**Preconditions:**
User is already registered in the system

**Acceptance criteria**

1. When I go to the login page and enter my username and password and click on Log in, then the data associated with my user role should be accessible

**Fields fulfill requirements**
Email address field: Max email length – 320 symbols; Min email length - 5 symbols; Recipient name shall consist of uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9, special characters ! # $ % & ' * + - / = ? ^ _ ` { | ( ) , : ; < > @ [ \ ]; A special character cannot appear as the first or last character in an email address or appear consecutively two or more times.  Presence of one @ symbol is obligatory. Domain name shall consist of uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9, hyphen (-), a period (.). The address has to have a period (.) symbol placed after the domain name before the top top-level domain in an email address.

Password: Max length – 128 symbols; Min length - 8 symbols; Symbols are uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9

[https://home-project-engineering.atlassian.net/browse/HP-15](url)

**Comment by maveric-ui** [comment]
FE: 24

**Comment by markuwas** [comment]
The real time that was spent on the task 42 hours, there were difficulties with the implementation of authorization (Vuex module)

**Comment by maveric-ui** [comment]
27.09.2021: 18 / 24 / 30

**Comment by maveric-ui** [comment]
#57
