### ISSUE TITLE
View the list of polls

### ISSUE THREAD

**Issue by yelgorkov** [ita-social-projects/Home-UI#306]
**As a cooperation admin I want to view the list of polls so that I can monitor the statuses of the polls**

**Preconditions**

Cooperation admin should be logged in.

Section “Polls“ must be opened.

**Acceptance Criteria**

The information that should be displayed in the Poll section:

- title;

- current status;

- start date;

- finish date

- votation result (“За”, “Проти“).

2. Statuses visibility:

- active - to all (cooperation admin and apartment owners of the selected houses);

- draft - to cooperation admin only;

- completed - to all (cooperation admin and apartment owners of the selected houses).

**Comment by yevhendevbox** [comment]
Merged to the develop branch.
