### ISSUE TITLE
Calculate poll results

### ISSUE THREAD

**Issue by yelgorkov** [ita-social-projects/Home-UI#343]
**As a cooperation admin I want to calculate poll results so that I can know if the decision was accepted or declined**

**Preconditions**

At least 1 vote should be made.

**Acceptance Criteria**

A question marker - the Cooperation admin selects if a question does not refer to such subjects using the radio buttons:

1.1. “Рішення про визначення переліку та розмірів внесків і платежів співвласників, порядок управління та користування спільним майном, передачу у користування фізичним та юридичним особам спільного майна, а також про реконструкцію та капітальний ремонт багатоквартирного будинку або зведення господарських споруд вважається прийнятим, якщо за нього проголосувало не менш як дві третини загальної кількості усіх співвласників”.

1.2. “Ті самі питання, але не передбачені Статутом ОСББ”.

1.3. “Інші питання”.

2. Enough number of votes for decision acceptance:

2.1. 2/3 of the total if the radio button 1.1 is selected.

2.2. More than 50% of the Total if the radio button 1.2 or 1.3 is selected.

2.3. If the ratio “за“ and “проти“ is like 50% on 50% the decision is not accepted.

3. Total percentage of votes - is calculated as s ratio between the number of votes made and the total number of apartment owners.

4. Check of a type of calculation - the system checks if there is an apartment owner who owns more than 50 % of the total apartments area of the house.

**If AC# 4 is TRUE the calculations rules are:**

Total number of votes “За“ - is calculated as a number of votes “За“.

Total number of votes “Проти“ - is calculated as a number of votes “Проти“

 **2. If AC# 4 is FALSE the calculations rules are:**

Total number of votes “За“ - is calculated as the area amount of votes “За“.

Total number of votes “Проти“ - is calculated as the area amount of votes “Проти“.

**Constraint:**

The law might be changed. It can lead to changes in the existing methodology of calculating the results of the voting.

**Comment by yevhendevbox** [comment]
Added radio buttons to create poll component.
