### ISSUE TITLE
[Bug Report] Breadcrumb navigation: Pointer is not displayed on the breadcrumb link after hovering 

### ISSUE THREAD

**Issue by NataHolembiovska** [ita-social-projects/Home-UI#355]
**Environment:** Windows 8×64, Firefox 97.0.1, Google Chrome 98.0.4758.102
**Reproducible:** always
**Build found:** https://home-project-ui.herokuapp.com

**Preconditions**
Cooperation admin is logged in

**Steps to reproduce**
1. Click on the 'Управління ОСББ' tab
2. Hover over some section of the breadcrumb link ( e.g. 'Квартири' section )
3. Pay attention to the specified section and the cursor  

**Actual result**
Text-cursor is shown on the breadcrumb link after hovering over the specified sections

**Expected result**
Pointer is shown on the breadcrumb link after hovering over the sections
The section of the breadcrumb link is highlighted on the general information section after hovering over it

**User story and test case links**
[Test case #7]( https://docs.google.com/spreadsheets/d/1MODP7F0bR8b4BDVF_BLUIdm9yh65gea4fV9-89DqnKA/edit#gid=0&range=38:42)
[User story #28]( https://home-project-engineering.atlassian.net/browse/HP-28 )

**Attachments**
https://user-images.githubusercontent.com/99169057/178228986-ac1c4c5e-6b4c-4a94-ada9-f4b816441ca5.mp4

**Comment by yevhendevbox** [comment]
Spend time: 1
Estimated time: 2
