### ISSUE TITLE
[Bug report] The updated information is not appear until user refresh the "Опитування" page

### ISSUE THREAD

**Issue by NataliiaMaistruk** [ita-social-projects/Home-UI#386]
**Environment:** Windows 10 Pro, Firefox 98.0., Google Chrome 105.0.5195.102.
**Reproducible:** always
**Build found:** https://home-project-ui.herokuapp.com/main

**Preconditions**
Cooperation admin is logged in
"Опитування" section is opened

**Steps to reproduce**
1. Choose the poll with status "draft" and click the settings button
2. Click on "Редагувати опитування" in dropdown list 
3. Fill all the required fields and press "Зберегти зміни" button
4. Pay attention to the edited poll (the poll is not updated)
5. Refresh the page
6. Pay attention to the edited poll again

**Actual result**
Information is updated after the page is refreshed

**Expected result**
Information is updated after "Зберегти зміни" button is pressed and "Редагувати опитування" modal window is closed

**Additional Information**
This bug is also reproduced when user chooses "Видалити опитування" option from dropdown list

**User story and test case links**
 "User story #42 https://home-project-engineering.atlassian.net/browse/HP-42

**Attachment**
https://images.zenhubusercontent.com/394645178/fe8a9c9d-6bfe-4f05-b418-49972f4ae747/home___google_chrome_2022_09_07_16_46_40.mp4

**Comment by Naira21** [comment]
Spent: 2
Remaining: 0

**Comment by Naira21** [comment]
UPD:
Spent: 82 hours
Remaining: 0
