### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by maveric-ui** [ita-social-projects/Home-UI#71]
Description
As a User I want to register in cooperation system so I can use the system.

Preconditions:
Сo-owners of apartment building association shall be created in system.
Cooperation admin should send invitation e-mail with redirection link and register key due to user role.

Acceptance criteria

E-mail with redirection link shall redirect user to registration page.
When e-mail is already register in the system - system shall propose user to login.
When redirection link is clicked user redirect to the registration page with requires to input fields: First name, Middle name, Last name, e-mail, password, confirm password, registration key.
When all form fields filled in correctly button “Register” becomes available.
User can login system with e-mail and password with rights due to his role.
Fields fulfill requirements
Email address field: Max email length – 320 symbols, Min email length - 5 symbols, Recipient name shall consist of uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9, special characters ! # $ % & ' * + - / = ? ^ _ ` { | ( ) , : ; < > @ [ \ ]
A special character cannot appear as the first or last character in an email address or appear consecutively two or more times.
Presence of one @ symbol is obligatory. Domain name shall consist of uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9, hyphen (-), a period (.)
The address has to have a period (.) symbol placed after the domain name before the top top-level domain in an email address.

First name, Middle name, Last name: Max length – 50 symbols. Min length - 1 symbol. Symbols are uppercase and lowercase letters (A-Z, a-z). Special characters ! # $ % & ' * + - / = ? ^ _ ` { | ( ) , : ; < > @ [ \ ]

Password:
Max length – 128 symbols
Min length - 8 symbol
Symbols are uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9

Password confirm: fields password and confirm password has to contain the same value.

Registration key (token): Length – 36 symbols. Symbols are uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9

https://home-project-engineering.atlassian.net/browse/HP-13

Flow_registerUser

**Comment by what-the-hub** [comment]
as discussed earlier (https://github.com/ita-social-projects/Home-UI/issues/22)
key validation was removed in the registration token field.
Fulfill of the ''Registration key'' field is obligatory.
