### ISSUE TITLE
Add new apartment

### ISSUE THREAD

**Issue by maveric-ui** [ita-social-projects/Home-UI#77]
As a cooperation admin I want to add new apartments to the list so that it can be used in ongoing processes

Preconditions
Cooperation admin should be logged in.

Section “Manage Cooperation“ section must be opened.

Acceptance Criteria

When the button “Add apartment” is pressed the modal window must be opened. 

The modal window must contain the inputs: the apartment number and the area size.

Buttons “save changes” and “discard changes” should be available at the bottom of the window.
Pressing “save changes” and “discard changes” buttons close a modal window with edit forms.

Fulfill requirements

Units of measurement: 

the area size - integer with 2 decimal places.

**Comment by Maria358** [comment]
Why is the story called "add new apartment", but the description says "When the button “ADD HOUSE” is pressed the modal window must be opened"?

**Comment by yelgorkov** [comment]
The US is updated.
