### ISSUE TITLE
Create poll

### ISSUE THREAD

**Issue by yelgorkov** [ita-social-projects/Home-UI#88]
**As a cooperation admin I want to create polls so that I can get to know the participants' opinions on the appropriate issue**

**Preconditions**

Cooperation admin should be logged in.

Section “Polls“ must be opened.

**Acceptance Criteria**

When the button “Create poll” is pressed the modal window should be opened.

The modal window should contain:

**input for a title.** The field is required, max length = 250 symbols, Cyrillic, any special symbols and figures are allowed;

**input for a long description (the poll purpose).**  The field is required, max length = 1000 symbols, Cyrillic, any special symbols and figures are allowed;

**a list of houses** included in the appropriate Cooperation;

**select the start date option**. The finish date is set as 15 days by default.

2. The cooperation admin selects the houses choosing the appropriate checkbox. Checkboxes must be unchecked by default. It’s required to choose at least 1 house.

3. The start date shouldn’t be earlier than the current date. A poll duration period should be equal to 15 calendar days (holidays are included). Any changes can be made only when the status is “Draft”.

4. Statuses “Active“, “Draft“, and “Completed“. 

The voting start date can't be current or previous. Status “Active” starts from 00:00:00 of the voting start date. The voting finish date is 23:59:59 on the 15th day since the start date. During the period before the start date, the poll stays as a draft. If the dates haven't been set the poll remains in “Draft” status. After 23:59:59 of the finish date, the status is “Completed“.

5. During the votation period an apartment owner can change their vote any number of times until the finish date.

6. When the status becomes “Active” the email is sent to apartment owners of the selected house immediately.

7. Buttons “save changes” and “discard changes” should be available at the bottom of the window.

Pressing “save changes” and “discard changes” buttons close a modal window with edit forms.

**Comment by yelgorkov** [comment]
![New Wireframe 1 (2).png](https://images.zenhubusercontent.com/6152eb21bb88b82ca873b193/72ad8108-7341-4822-98f5-38900eaba6b3)

**Comment by iomel88** [comment]
FYI @yelgorkov, @AnnaGlovyak  the changes have been done to the forth bullet refering to statuses.
Status “Active” starts from 00:00:00 of the date set as start of voting ( the start date can't be current or previous) The start date and time is served as a trigger for emails to be sent to apartment owners. The finish of voting date is the (23:59:59) on the15ths day from the start of voting date. During the period before the start date, the poll stays as a draft. If the dates haven't been set the poll remains in “Draft” status. After (23:59:59) of the finish of voting date, the poll becomes “Completed“.
If changes by cooperation admin are made the start date updates as it’s mentioned in AC #4. **(TBD with Yelisey)**

**Comment by yelgorkov** [comment]
Updated:
1) deleted question section
2) in title 250 symbols
3) #4 - Active is clarified

**Comment by yelgorkov** [comment]
Hello!
Updated:
about start date
this US has been divided into two US (this and "View the list of polls")
